### ISSUE TITLE
Top-level browser elements not showing

### ISSUE THREAD

**Issue by kflak** [mpdel/mpdel#17]
Hi, and thanks for a great package! I'm just starting my emacs journey after a decade of vimming, so I was very happy to find an mpd client for emacs as well...

The browser works well, but the appearance is nothing like the picture in the readme... I am running with vanilla config.

Any idea what I'm doing wrong here? This is what I get when I hit `:` or `M-x mpdel-browser-open`

![2024-07-10_14:48:22](https://github.com/mpdel/mpdel/assets/13571232/f991e2ec-cb82-450e-a9d7-644be92736ef)

**Comment by DamienCassou** [comment]
hi @kflak,

welcome to the Emacs community and sorry for not answering you earlier. What I see in your screenshot is reasonable. Here is what is looks like in mine:

![image](https://github.com/user-attachments/assets/af6bfbab-0a77-4d31-aa68-43629e728459)


What you see in the screenshot of the README is 2 windows: on the left the browser and on the right the playlist:
![image](https://github.com/user-attachments/assets/cb3d62e8-c3a7-420e-a97b-4b003111e414)

You can open another window with `C-x 3` (this is standard Emacs and has nothing to do with mpdel).

**Comment by kflak** [comment]
Thanks a lot! It's all starting to click into focus now :-) Was fiddling around a bit with emms as well, but turns out that package has no way of categorizing m4a-files, which is a big part of my music collection. So I'm back to mpdel :smile:

**Comment by DamienCassou** [comment]
Enjoy. Feel free to open new issues.
