### ISSUE TITLE
Move cursor to top after opening {browser,playlist,music directory,etc}

### ISSUE THREAD

**Issue by kflak** [mpdel/mpdel#20]
Very minor nag, but I would love it if the cursor was placed on the top of the buffer after opening the browser/playlist/directory view etc... Small change, but added up over time it would provide a large lift in quality of life.

**Comment by DamienCassou** [comment]
That's a good idea @kflak, thanks for reaching out. I think I've just fixed that in https://github.com/DamienCassou/navigel/pull/4 which is released in v1.0 of navigel.

Feel free to reopen if there is still an issue.

**Comment by kflak** [comment]
Cool, thanks a lot! This seems to solve the issue.
